# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase恢复商品属性(HttpRunner):

    config = Config("恢复商品属性").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "goodsId": 144508,
        })

    teststeps = [
        Step(
            RunRequest("/test_t/ppy-op-api/goods/changeRecycledStatus")
            .post(
                "/ppy-op-api/goods/changeRecycledStatus"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "31",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"goodsId": "$goodsId", "recycled": False})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                "body.traceMsg",
                "underlying service internal biz exception, traceId: 1603194928408, exception occurred at application: ppy-op-core, serviceName: changeRecycledStatus",
            )
        ),
    ]


if __name__ == "__main__":
    TestCase恢复商品属性().test_start()
